Users/login
TheBobu/ProiectInginerieSoftware pull request #9
Opened 2021-01-09 18:08 UTC by TheBobu

Added 
- login 
- logout
- administrator area with manage users
- user bean
- roles(please check the xml) 
- realm(PLEASE IMPLEMENT AS INSTRUCTED)

2021-01-09 18:10 UTC, andreeapurta approved these changes

2021-01-09 19:28 UTC, DeeaMatei approved these changes
Looking good :octocat:

2021-01-09 20:30 UTC, robert-stoian approved these changes

2021-01-09 22:15 UTC, LeUnicorn commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/common/DetachedEntity.java
> +}
o poti sterge

2021-01-09 22:15 UTC, LeUnicorn commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/login/servlet/Login.java
> +        request.setAttribute("message", "Username or password incorrect");
🦖

2021-01-09 22:15 UTC, LeUnicorn commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/user/ejb/UserBean.java
> +}
de for-urile astea se ocupa helperul detachEntities, entitatea ta trebe doar sa implementeze interfata Detachable si sa returneze din metoda un obiect UserDetails

2021-01-09 22:15 UTC, LeUnicorn commented on JobRecruiting/JobRecruiting/src/main/webapp/WEB-INF/web.xml
> +    </login-config>
asta trebe sa il ciodesc :))

2021-01-09 22:15 UTC, LeUnicorn commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/login/servlet/Login.java
> +        request.setAttribute("message", "Username or password incorrect");
Cred ca va fi mereu acolo

2021-01-11 11:40 UTC, DoLyFaur requested changes
Unde am inteles ce era pe acolo si mi s-a parut ca mai trebuie schimbat, am comentat...

2021-01-11 11:40 UTC, DoLyFaur commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/common/DetachedEntity.java
> +}
Asta e goala...ramane asa?

2021-01-11 11:40 UTC, DoLyFaur commented on JobRecruiting/JobRecruiting/src/main/webapp/index.jsp
> +
Aici aveam si eu liniile alea cu buoanele de login si register...nu le mai punem?

2021-01-11 11:40 UTC, DoLyFaur commented on JobRecruiting/JobRecruiting/src/main/webapp/WEB-INF/pages/jobpost/jobpost.jsp
> +</t:pageTemplate>
Avem nevoie de asta?

2021-01-11 11:40 UTC, DoLyFaur commented on JobRecruiting/JobRecruiting/src/main/webapp/WEB-INF/glassfish-web.xml
> +    <group-name>CANDIDATE</group-name>
Lipseste directorul de HR. Vezi doc asta de pe drive - https://docs.google.com/spreadsheets/d/1jPem4IYcY2YCJ5Kqh46CRRtrZ_H7dvMG/edit#gid=1663931403

2021-01-11 11:40 UTC, DoLyFaur commented on JobRecruiting/JobRecruiting/src/main/java/com/recruit/jobrecruiting/entity/Position.java
> +}
Vad ca nici aici nu e directorul de HR. Si am discutat de el la UserStory, deci poate ca ar fi bine sa il punem
https://docs.google.com/spreadsheets/d/1jPem4IYcY2YCJ5Kqh46CRRtrZ_H7dvMG/edit#gid=1663931403

2021-01-11 12:33 UTC, merged